### ISSUE TITLE
Event buffers are deprecated

### ISSUE THREAD

**Issue by mxmilkiib** [adsr/lv2h#1]
I mentioned this project in #lv2 on Freenode and it was noted in a response that LV2 event buffers have been deprecated since 2012 : http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2014-January/000642.html

**Comment by adsr** [comment]
Hello, thanks for checking out the project. `lv2_evbuf.c` is copied from Ardour trunk minus any code related to `LV2_Event*` which I believe is the deprecated standard. Please re-open if I have this confused. Thanks again.
